### ISSUE TITLE
Why are you clearing the buffer instead of waiting for more data?

### ISSUE THREAD

**Issue by leopucci** [vondraussen/gt06#19]
Hello, 
In your code you clear the buffer
```
 gt06.msgBuffer.forEach(msg => {
      console.log(msg);
    });

    gt06.clearMsgBuffer()   <===== HERE
```

If a message is sent partially you are going to drop it insetad of waiting for the rest and managing to get the whole message

**Comment by vondraussen** [comment]
@leopucci feel free to create a PR with test.

**Comment by notesMafia** [comment]
how to run gt06 decoder i install node.js and vs code but it dont work please give some guide so i can run gt06 decoder

**Comment by notesMafia** [comment]
my mail id is notesharbourgju@gmail.com

**Comment by leopucci** [comment]
the code is working properly friend, just run and receive the messages

**Comment by notesMafia** [comment]
![Capture](https://github.com/vondraussen/gt06/assets/132620177/e6a2b0c0-339c-46b2-a2d7-a0a0f5424d85)

**Comment by notesMafia** [comment]
get location on my mobile by text but not here help me

**Comment by notesMafia** [comment]
https://github.com/vondraussen/gt06/issues/19

check this please
