### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by PepeBel4** [vondraussen/gt06#9]
Hello,
I would like to find out more how to actually run this; how to set up server to catch this data and respond to the trackers with correct info.

**Comment by vondraussen** [comment]
Hi @PepeBel4,
please take a look at https://github.com/vondraussen/gps_tracker_gateway
Where I use this lib.

**Comment by PepeBel4** [comment]
Hello,

Thank you, I had a look last night and managed to get it running and receiving some data from trackers,
Cool!

Many thanks,
Best regards,
Pascal
